language: python
sudo: required
python:
  - "2.7"
  - "3.3"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"
 
services:
  - docker

env:
  matrix:
    - KV_DB=redis
    - KV_DB=zookeeper

# command to install dependencies
install: 
  - "pip install nstruct hiredis"
  - pip install coverage

cache:
  directories:
    - cache
    
    
# command to run tests
script: 
  - sudo -H -E bash -xe ci_test.sh


