language: python
sudo: required
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
services:
  - docker

env:
  matrix:
    - KV_DB=redis
    - KV_DB=zookeeper

# command to install dependencies
install: "pip install nstruct hiredis"
# command to run tests
script: sudo bash -xe ci_test.sh
